# Generated by Django 4.1.7 on 2023-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_car_id_alter_car_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="price", field=models.IntegerField(),
        ),
    ]
